classifier:
  model_config:
    - class: "BaselineModel"
    - class: "SpacyModel"
      args:
        config_path: data/05_model_input/spacy_config.cfg
        trained_pipeline_name: de_core_news_sm
    - class: "RandomForestClassifierModel"
  input_features: ['text', 'spacy_doc']
  predict_feature: "Brief"
  selection_score: "balanced_accuracy"
  train_percentage: 90

clustering:
  model_config:
    - class: "BaselineModel"
    - class: "SpacyKMeansModel"
  input_features: ['text', 'spacy_doc']
  selection_score: "calinski_harabasz_score"
  train_percentage: 90

data_processing:
  max_workers: 4
  spacy_model: de_core_news_sm
